#!/usr/bin/env bash
# code-review-graph setup — auto-generated by crg-dev-kit
pip install code-review-graph 2>/dev/null || pipx install code-review-graph
python -m code_review_graph install --platform claude-code
python -m code_review_graph build
echo "code-review-graph ready."
