name = "madinah-vape-landing"
main = "worker.js"
compatibility_date = "2026-04-23"

routes = [
  { pattern = "saudivapes.com/ar/متجر-فيب-المدينة-المنورة*", zone_name = "saudivapes.com" },
  { pattern = "saudivapes.com/متجر-فيب-المدينة-المنورة*", zone_name = "saudivapes.com" }
]
